language: go

go:
  - 1.6
  - 1.9

sudo: false

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - go get github.com/satori/go.uuid
  - go get github.com/gorilla/websocket
  - go get github.com/mattn/goveralls

script:
  - go test -cover -coverprofile=coverage.out -v ./wsrpc/
  - goveralls -coverprofile=coverage.out -service travis-ci
